const products=[{id:'p1',name:'Coxinha',price:6.5},{id:'p2',name:'Pastel',price:8.0},{id:'p3',name:'Refrigerante',price:5.0}];
const productListEl=document.getElementById('productList'),cartItemsEl=document.getElementById('cartItems'),totalEl=document.getElementById('total'),orderForm=document.getElementById('orderForm'),mensagemEl=document.getElementById('mensagem'),clearCartBtn=document.getElementById('clearCartBtn');let cart={};
function formatCurrency(v){return Number(v).toFixed(2);}
function renderProducts(){productListEl.innerHTML='';products.forEach(p=>{const div=document.createElement('div');div.className='product';div.innerHTML=`<strong>${p.name}</strong><div>R$ ${formatCurrency(p.price)}</div><button class='btn' data-id='${p.id}'>Adicionar</button>`;productListEl.appendChild(div);});}
productListEl.addEventListener('click',e=>{const id=e.target.dataset.id;if(!id)return;const prod=products.find(p=>p.id===id);cart[id]=cart[id]?{...prod,qty:cart[id].qty+1}:{...prod,qty:1};renderCart();});
function renderCart(){cartItemsEl.innerHTML='';let total=0;Object.values(cart).forEach(i=>{cartItemsEl.innerHTML+=`<li>${i.name} x ${i.qty}</li>`;total+=i.price*i.qty;});totalEl.textContent=formatCurrency(total);}
clearCartBtn.onclick=()=>{cart={};renderCart();};
orderForm.onsubmit=async e=>{e.preventDefault();const nome=orderForm.nome.value.trim(),telefone=orderForm.telefone.value.trim(),endereco=orderForm.endereco.value.trim(),items=Object.values(cart).map(i=>`${i.name} x ${i.qty}`).join(', '),total=`R$ ${totalEl.textContent}`;if(!items){mensagemEl.textContent='Carrinho vazio.';return;}
try{const res=await fetch('/.netlify/functions/enviarParaNotion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome,telefone,endereco,items,total})});const data=await res.json();if(res.ok){mensagemEl.textContent='✅ Pedido enviado!';cart={};renderCart();orderForm.reset();}else{mensagemEl.textContent=`❌ Erro: ${data.error||data.message}`;console.log('Detalhes do erro:',data);}}
catch(err){mensagemEl.textContent='❌ Erro de conexão';console.error(err);}};
renderProducts();